/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificacionesTurno0900RouteImport } from './routes/notificaciones.turno-0900'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesTurno0900Route = NotificacionesTurno0900RouteImport.update({
  id: '/notificaciones/turno-0900',
  path: '/notificaciones/turno-0900',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notificaciones/turno-0900': typeof NotificacionesTurno0900Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notificaciones/turno-0900': typeof NotificacionesTurno0900Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notificaciones/turno-0900': typeof NotificacionesTurno0900Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notificaciones/turno-0900'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notificaciones/turno-0900'
  id: '__root__' | '/' | '/notificaciones/turno-0900'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificacionesTurno0900Route: typeof NotificacionesTurno0900Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones/turno-0900': {
      id: '/notificaciones/turno-0900'
      path: '/notificaciones/turno-0900'
      fullPath: '/notificaciones/turno-0900'
      preLoaderRoute: typeof NotificacionesTurno0900RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificacionesTurno0900Route: NotificacionesTurno0900Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
